#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Particle {
    vec4 position;
    vec4 velocity;
    float mass;
    int id;
};

layout(set = 0, binding = 8) buffer ParticleData 
{
    Particle data[];
};

void main() 
{
    uint id = gl_GlobalInvocationID.x;
    if (id < 200) // Ensure we're within bounds
    {
        data[id].id = 5; // Set the ID for the current particle
    }
}